bootstrap_servers:
  - localhost:9092
validate:
  in:
    SomeConsumer.function1:
        type: object
        properties:
            asd:
              - type: string
    DEFAULT_GROUP.function2:
        type: object
        properties:
            asd:
              - type: string
  out:
